test_get_airport (api_test.TestAWCAPI.test_get_airport) ... FAIL
test_get_airsigmet (api_test.TestAWCAPI.test_get_airsigmet) ... FAIL
test_get_areafcst (api_test.TestAWCAPI.test_get_areafcst) ... ok
test_get_cwa (api_test.TestAWCAPI.test_get_cwa) ... ok
test_get_fcstdisc (api_test.TestAWCAPI.test_get_fcstdisc) ... ok
test_get_feature (api_test.TestAWCAPI.test_get_feature) ... FAIL
test_get_gairmet (api_test.TestAWCAPI.test_get_gairmet) ... ok
test_get_isigmet (api_test.TestAWCAPI.test_get_isigmet) ... FAIL
test_get_metar (api_test.TestAWCAPI.test_get_metar) ... FAIL
test_get_mis (api_test.TestAWCAPI.test_get_mis) ... ok
test_get_obstacle (api_test.TestAWCAPI.test_get_obstacle) ... FAIL
test_get_pirep (api_test.TestAWCAPI.test_get_pirep) ... ok
test_get_stationinfo (api_test.TestAWCAPI.test_get_stationinfo) ... ok
test_get_taf (api_test.TestAWCAPI.test_get_taf) ... ok
test_get_windtemp (api_test.TestAWCAPI.test_get_windtemp) ... ok

======================================================================
FAIL: test_get_airport (api_test.TestAWCAPI.test_get_airport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\jamie\Documents\GitHub\ToolsForTheJobBenchmark\generation\Weather\awc\api_test.py", line 64, in test_get_airport
    self.assertTrue(isinstance(response, dict))
AssertionError: False is not true

======================================================================
FAIL: test_get_airsigmet (api_test.TestAWCAPI.test_get_airsigmet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\jamie\Documents\GitHub\ToolsForTheJobBenchmark\generation\Weather\awc\api_test.py", line 28, in test_get_airsigmet
    self.assertTrue(isinstance(response, dict))
AssertionError: False is not true

======================================================================
FAIL: test_get_feature (api_test.TestAWCAPI.test_get_feature)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\jamie\Documents\GitHub\ToolsForTheJobBenchmark\generation\Weather\awc\api_test.py", line 68, in test_get_feature
    self.assertTrue(isinstance(response, dict))
AssertionError: False is not true

======================================================================
FAIL: test_get_isigmet (api_test.TestAWCAPI.test_get_isigmet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\jamie\Documents\GitHub\ToolsForTheJobBenchmark\generation\Weather\awc\api_test.py", line 32, in test_get_isigmet
    self.assertTrue(isinstance(response, dict))
AssertionError: False is not true

======================================================================
FAIL: test_get_metar (api_test.TestAWCAPI.test_get_metar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\jamie\Documents\GitHub\ToolsForTheJobBenchmark\generation\Weather\awc\api_test.py", line 16, in test_get_metar
    self.assertTrue(isinstance(response, dict))
AssertionError: False is not true

======================================================================
FAIL: test_get_obstacle (api_test.TestAWCAPI.test_get_obstacle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\jamie\Documents\GitHub\ToolsForTheJobBenchmark\generation\Weather\awc\api_test.py", line 72, in test_get_obstacle
    self.assertTrue(isinstance(response, dict))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 15 tests in 6.543s

FAILED (failures=6)

======================================================================
